# Generated by Django 4.0.7 on 2022-08-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='id',
        ),
        migrations.AddField(
            model_name='operations',
            name='Activated',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='ActivationCode',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='CheckedDt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='CheckedOn',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='ExpiryDate',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='MacAddress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='SerialNumber',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='SrNo',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='StartDate',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
