# Generated by Django 4.0.7 on 2022-08-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0002_remove_operations_id_operations_activated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='Activated',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='ActivationCode',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='CheckedDt',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='CheckedOn',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='ExpiryDate',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='MacAddress',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='SerialNumber',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='SrNo',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='StartDate',
        ),
        migrations.AddField(
            model_name='operations',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
