# Generated by Django 4.0.7 on 2022-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0004_remove_operations_id_operations_activated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='brillentsec',
            fields=[
                ('SrNo', models.AutoField(primary_key=True, serialize=False)),
                ('SerialNumber', models.CharField(max_length=500, null=True)),
                ('CompName', models.CharField(max_length=500, null=True)),
                ('ActivationCode', models.CharField(max_length=500, null=True)),
                ('ExpiryDate', models.CharField(max_length=500, null=True)),
                ('StartDate', models.CharField(max_length=500, null=True)),
                ('CheckedOn', models.CharField(max_length=500, null=True)),
                ('MacAddress', models.CharField(max_length=500, null=True)),
                ('Activated', models.CharField(max_length=500, null=True)),
                ('CheckedDt', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'brillentsec',
            },
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
    ]
