# Generated by Django 4.0.7 on 2022-08-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0005_brillentsec_delete_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brillentsec',
            name='ExpiryDate',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brillentsec',
            name='StartDate',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
