# Generated by Django 4.0.7 on 2022-08-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0007_alter_brillentsec_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brillentsec',
            name='ExpiryDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='brillentsec',
            name='StartDate',
            field=models.DateField(),
        ),
    ]
