# Generated by Django 4.0.7 on 2022-08-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0009_alter_brillentsec_expirydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brillentsec',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brillentsec',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
