# Generated by Django 4.0.7 on 2022-08-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0010_brillentsec_password_brillentsec_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='brillentsec',
            name='confirm_password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
