# Generated by Django 4.0.7 on 2022-08-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0011_brillentsec_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedcalcusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=500, null=True)),
                ('confirm_password', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'feedcalcusers',
            },
        ),
    ]
