# Generated by Django 4.0.7 on 2022-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0012_feedcalcusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcalcusers',
            name='Id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
