# Generated by Django 4.0.7 on 2022-08-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0013_feedcalcusers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brillentsec',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='brillentsec',
            name='password',
        ),
        migrations.RemoveField(
            model_name='brillentsec',
            name='username',
        ),
    ]
