# Generated by Django 4.0.7 on 2022-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0014_remove_brillentsec_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedcalcusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='feedcalcusers',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
