# Generated by Django 4.2.6 on 2024-04-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0015_remove_feedcalcusers_id_alter_feedcalcusers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcalcusers',
            name='adminflg',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
