# Generated by Django 4.2.6 on 2024-04-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oper', '0016_feedcalcusers_adminflg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedcalcusers',
            name='adminflg',
        ),
    ]
